Fix "Undefined array key _ in Otl.php:1542"
mpdf/mpdf pull request #1962
Opened 2023-11-30 14:14 UTC by sonnymilton

Checking the existence of the offset

Closes #1963

2023-11-30 15:01 UTC, sonnymilton commented
Hello @finwe,

I have added the test case as you requested in the test/Issues directory. This test checks for the absence of warnings when creating a PDF, as related to my changes.

Please let me know if anything else is needed or if you have any comments/suggestions on my PR.

2023-12-01 21:13 UTC, finwe requested changes
Looking fine apart from a few minor enhancements. Please resolve these, squash the commits and I'll be happy to merge.

2023-12-01 21:13 UTC, finwe commented on src/Otl.php
> +								if (!($this->OTLdata[$ptr]['mask'] & $mask) || !isset($this->OTLdata[$ptr + 1])) {
Can you make the condition separate so that the code is more readable?

2023-12-01 21:13 UTC, finwe commented on tests/Issues/Issue1963Test.php
> +	protected function set_up()
This method is kind of unnecessary, make a local variable directly in the test method.

2023-12-01 21:13 UTC, finwe commented on tests/Issues/Issue1963Test.php
> +		$output = $this->mpdf->Output('my.pdf', Destination::STRING_RETURN);
Maybe use the shorthand [OutputBinaryData()](https://mpdf.github.io/reference/mpdf-functions/outputbinarydata.html) directly? the filename is unnecessary here.

2023-12-01 21:13 UTC, finwe commented on tests/Issues/Issue1963Test.php
> +
Only a single empty line, please (should have been caught in code style check)

2023-12-02 11:22 UTC, sonnymilton commented
@finwe,

I have made the requested changes to the PR. 
Please review the latest updates and let me know if anything else is required.

2023-12-04 15:58 UTC, merged

2023-12-05 09:52 UTC, sonnymilton commented
Hello @finwe,

I am glad that my PR has been merged. I believe that many library users could benefit from this change.

I would like to ask you to publish a new version with these changes so that I and other users can take advantage of these improvements in our projects.